/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWizardRouteImport } from './routes/_layout/wizard'
import { Route as LayoutVendorsRouteImport } from './routes/_layout/vendors'
import { Route as LayoutReviewsRouteImport } from './routes/_layout/reviews'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutPpwrRouteImport } from './routes/_layout/ppwr'
import { Route as LayoutEpdRouteImport } from './routes/_layout/epd'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutRolesIndexRouteImport } from './routes/_layout/roles/index'
import { Route as LayoutUsersNewRouteImport } from './routes/_layout/users/new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWizardRoute = LayoutWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVendorsRoute = LayoutVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewsRoute = LayoutReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPpwrRoute = LayoutPpwrRouteImport.update({
  id: '/ppwr',
  path: '/ppwr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEpdRoute = LayoutEpdRouteImport.update({
  id: '/epd',
  path: '/epd',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRolesIndexRoute = LayoutRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersNewRoute = LayoutUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/epd': typeof LayoutEpdRoute
  '/ppwr': typeof LayoutPpwrRoute
  '/projects': typeof LayoutProjectsRoute
  '/reviews': typeof LayoutReviewsRoute
  '/vendors': typeof LayoutVendorsRoute
  '/wizard': typeof LayoutWizardRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/roles/': typeof LayoutRolesIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/epd': typeof LayoutEpdRoute
  '/ppwr': typeof LayoutPpwrRoute
  '/projects': typeof LayoutProjectsRoute
  '/reviews': typeof LayoutReviewsRoute
  '/vendors': typeof LayoutVendorsRoute
  '/wizard': typeof LayoutWizardRoute
  '/': typeof LayoutIndexRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/roles': typeof LayoutRolesIndexRoute
  '/users': typeof LayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/epd': typeof LayoutEpdRoute
  '/_layout/ppwr': typeof LayoutPpwrRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/reviews': typeof LayoutReviewsRoute
  '/_layout/vendors': typeof LayoutVendorsRoute
  '/_layout/wizard': typeof LayoutWizardRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/users/new': typeof LayoutUsersNewRoute
  '/_layout/roles/': typeof LayoutRolesIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/epd'
    | '/ppwr'
    | '/projects'
    | '/reviews'
    | '/vendors'
    | '/wizard'
    | '/users/new'
    | '/roles/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/epd'
    | '/ppwr'
    | '/projects'
    | '/reviews'
    | '/vendors'
    | '/wizard'
    | '/'
    | '/users/new'
    | '/roles'
    | '/users'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/epd'
    | '/_layout/ppwr'
    | '/_layout/projects'
    | '/_layout/reviews'
    | '/_layout/vendors'
    | '/_layout/wizard'
    | '/_layout/'
    | '/_layout/users/new'
    | '/_layout/roles/'
    | '/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wizard': {
      id: '/_layout/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof LayoutWizardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vendors': {
      id: '/_layout/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof LayoutVendorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reviews': {
      id: '/_layout/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof LayoutReviewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ppwr': {
      id: '/_layout/ppwr'
      path: '/ppwr'
      fullPath: '/ppwr'
      preLoaderRoute: typeof LayoutPpwrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/epd': {
      id: '/_layout/epd'
      path: '/epd'
      fullPath: '/epd'
      preLoaderRoute: typeof LayoutEpdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roles/': {
      id: '/_layout/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof LayoutRolesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/new': {
      id: '/_layout/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof LayoutUsersNewRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutEpdRoute: typeof LayoutEpdRoute
  LayoutPpwrRoute: typeof LayoutPpwrRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutReviewsRoute: typeof LayoutReviewsRoute
  LayoutVendorsRoute: typeof LayoutVendorsRoute
  LayoutWizardRoute: typeof LayoutWizardRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutUsersNewRoute: typeof LayoutUsersNewRoute
  LayoutRolesIndexRoute: typeof LayoutRolesIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEpdRoute: LayoutEpdRoute,
  LayoutPpwrRoute: LayoutPpwrRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutReviewsRoute: LayoutReviewsRoute,
  LayoutVendorsRoute: LayoutVendorsRoute,
  LayoutWizardRoute: LayoutWizardRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutUsersNewRoute: LayoutUsersNewRoute,
  LayoutRolesIndexRoute: LayoutRolesIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
